default: about
variants:
- name: about
  context:
    title: "About 24 ways"
    section: about
    sections:
    - id: background
      title: Background
      content: |
        <p class="lede">24 ways is the advent calendar for web geeks. For twenty-four days each December we publish a daily dose of web design and development goodness to bring you all a little Christmas cheer.</p>

        Back in December 2005, Drew McLellan set up what he called "a festive blog" with a new article each day written by experts sharing their knowledge. Articles present ideas, techniques or experiences that you can take and apply to your own work. Code snippets, advice about business and clients, workflow and workshopping, design inspiration: 24 ways has it all.

        With over one hundred authors and almost two hundred articles, 24 ways is very proud to have become an annual fixture in the calendars of web geeks. Since 2005, 24 ways has always combined learning and sharing, both vital aspects of the continued strength of the web community. As Drew wrote, ‘There’s a lot of fun to be had in learning something that will impress those you work with – especially if then you can share what you know to everyone’s benefit.’
    - id: credits
      title: Credits
      content: |
        * 24 ways is brought to you by Perch and is built on [Perch Runway](https://grabaperch.com/?ref=24w01)
        * Produced by [Drew McLellan](http://allinthehead.com/), [Brian Suda](http://suda.co.uk/), [Anna Debenham](http://maban.co.uk/) and [Owen Gregory](http://fullcreammilk.co.uk/).
        * Designed by [Paul Robert Lloyd](https://paulrobertlloyd.com/).
        * Possible only with the help and dedication of [our authors](/authors/).
    - id: colophon
      title: Colophon
      content: |
        * Content managed with [Perch Runway](https://grabaperch.com/?ref=24w01).
        * Hosted by [Memset Dedicated Servers](https://www.memset.com/dedicated-servers/).
        * Standing on the shoulders of Varnish, Nginx, Apache, PHP, MySQL, Amazon S3 and CloudFront.
        * Type set in [Source Sans Pro](https://adobe-fonts.github.io/source-sans-pro/), [Source Serif Pro](https://adobe-fonts.github.io/source-serif-pro/) and [Source Code Pro](https://adobe-fonts.github.io/source-code-pro/) by Adobe.
        * Fonts served via [Google Fonts](https://fonts.google.com/).
        * [Minicons](http://www.webalys.com/minicons/) by Vincent Le Miogn.
        * [prism.js](https://github.com/leaverou/prism/) by Lea Verou.
- name: "404"
  context:
    title: "404"
    sections:
    - id: error
      title: Page not found
      content: |
        <p class="lede">Sorry, but we can't find that page.</p>

        The page you requested wasn't found in the location specified. You may have an incorrect URL, or the file could have been moved or renamed.

        If you're having problems finding a particular page, try searching the site or return to the homepage.
    - id: search
      title: Search 24 ways
      component: search-form
- name: sponsorship
  context:
    title: "Sponsoring 24 ways"
    section: sponsorship
    sections:
    - id: sponsorship
      title: Sponsorship
      content: |
        <p class="lede">For thirteen years, 24 ways has been a fixture of the web design and development calendar, providing fresh and interesting artiles thoughout the month of December.</p>

        All our authors and the production team give up their time and skills for free as a gift to the industry. We do have out-of-pocket expenses, however, which provides an opportunity for like-minded companies to partner with us and bring this valuable resource to our readers.

        Each article carries just a single, non-animated 150px@2x graphic ad with brief accompanying text. Rather than running for just one day, this ad runs for the lifetime of the article it accompanies. That’s potentially years of advertising for just one flat payment. We’ll also include the ad in our RSS feed and post to our social media accounts.

        Available days are listed below. If you’d like to discuss sponsoring one or more articles, please [drop us a line](#) to discuss.
    - id: slots
      title: Available slots
      component: listing
      config:
        mods: [summaries]
        component: summary
        items:
        - "@summary--sponsored"
        - "@summary--sponsored-taken"
        - "@summary--sponsored"
        - "@summary--sponsored"
