collated: true
context:
  theme: day-15
  href: /2015/grid-flexbox-box-alignment-our-new-system-for-layout/
  title: "Grid, Flexbox, Box Alignment: Our New System for Layout"
  author: Rachel Andrew
  datetime: "2010-12-15T00:00:00-00:00"
  comments: 6
  content: |
    [Rachel Andrew](https://rachelandrew.co.uk/) unwraps the new paradigms of web layout, comparing their features and showing how they can free us from grid-based, `div`-infested frameworks. Beautifully wrapped boxes look lovely under the Christmas tree, but we need to think and break out of them.
variants:
- name: countdown
  context:
    mods: [countdown]
    theme: day-15
    href: /2010/real-animation-using-javascript-css3-and-html5-video/
    title: "Real Animation Using JavaScript, CSS3, and HTML5 Video"
    author: Dan Mall
    datetime: "2010-12-15T00:00:00-00:00"
    comments: 11
    content: |
      [Dan Mall](http://danielmall.com/) breathes life into web standards-based animation. By striving for more than just mechanical movement, we can create more believable animated effects to enhance our users' experience.
- name: short
  context:
    mods: [countdown]
    theme: day-15
    href: /2010/real-animation-using-javascript-css3-and-html5-video/
    title: "Real Animation"
    author: Dan Mall
    datetime: "2010-12-15T00:00:00-00:00"
    comments: 11
    content: |
      *Dan Mall* breathes life into web standards-based animation.
- name: sponsored
  context:
    mods: [sponsored]
    href: mailto:sponsorship@24ways.org?subject=Sponsoring 24 ways on Friday, 1 December
    title: "Friday, 1 December"
    author: false
    datetime: false
    content: |
      Sponsor this day for $250 <abbr title="US Dollars">USD</abbr>.
- name: sponsored-taken
  context:
    mods: [sponsored, taken]
    href: false
    title: "Saturday, 2 December"
    author: false
    datetime: false
    content: |
      Too late, this slot has been taken!
